# Generated by Django 4.2.7 on 2024-02-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукцию', 'verbose_name_plural': 'Продукция'},
        ),
    ]
